version: "3"

networks:
  course-platform:
    external: true

services:
  
  nginx:
    image: nginx-proxy
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: "50M"
    networks:
      - course-platform

  seq:
    container_name: seq
    image: datalust/seq
    ports:
      - "50505:80"
    volumes:
      - /home/actions/masters/seq:/data
    environment:
      ACCEPT_EULA: "Y"
      SEQ_API_CANONICALURI: "https://birdegop.ru/logs"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "300M"
    networks: 
      - course-platform
  
  prometheus:
    container_name: prometheus
    build:
      context: .
      dockerfile: Prometheus.Dockerfile
    user: root
    volumes:
      - /home/actions/course-platform/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.config.file=/etc/prometheus/prometheus.web.yml'
      - '--web.external-url=/prometheus/'
      - '--web.route-prefix=/'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "100M"
    networks:
      - course-platform
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    volumes:
      - /home/actions/course-platform/grafana:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: http://localhost:3000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "100M"
    depends_on:
      - prometheus
    networks:
      - course-platform

  postgres:
    image: postgres
    container_name: postgres
    environment:
      # Don't worry, these are overriden by github runner
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - /home/actions/course-platform/pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "200M"
    ports:
      - "5432:5432"
    networks: 
      - course-platform
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    environment:
      # Don't worry, these are overriden by github runner
      DATA_SOURCE_NAME: "postgresql://postgres:root@postgres:5432/?sslmode=disable"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20M"
    depends_on:
      - postgres
      - prometheus
    networks:
      - course-platform
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "100M"
    networks:
      - course-platform

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    hostname: kafka
    environment:
      # kafka just loves not working. when I added OVERSEAS i had to debug 3 hours the "Leader not available" error in kafkacat.
      # i have just completely erased zookeeper volume and restarted it with kafka, and it magically worked
      # If ever you have a similar problem, 
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093,OVERSEAS://kafka.birdegop.ru:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT,OVERSEAS:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093,OVERSEAS://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500M"
    volumes:
      - /home/actions/course-platform/kafka:/kafka
    ports:
      - "9094:9094"
    networks:
      - course-platform

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            course-platform:
              properties:
                bootstrap.servers: "kafka:9092"
        micronaut:
          server:
            context-path: "/kafka"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "300M"
    networks:
      - course-platform
    depends_on:
      - kafka

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-in-docker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      SERVER_SERVLET_CONTEXT_PATH: /kafka2
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "300M"
    networks:
      - course-platform
    depends_on:
      - kafka
  
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20M"
    networks:
      - course-platform
    volumes:
      - '/:/host:ro,rslave'
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    restart: unless-stopped
    container_name: cadvisor
    devices:
      - "/dev/kmsg:/dev/kmsg"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100M"
    networks:
      - course-platform