global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'main-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['main-server:80']

  - job_name: node-exporter
    static_configs:
      - targets: [ 'localhost:9100' ]

  - job_name: postgres-exporter
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]