name: Deploy egop runner

on:
  push:
    branches: [ "master", "develop" ]

jobs:
        
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: create prometheus auth yml
        env:
          PROMETHEUS_AUTH: ${{ secrets.PROMETHEUS_AUTH }}
        run: | 
          echo 'basic_auth_users:' > prometheus.web.yml
          echo "  admin: \"${PROMETHEUS_AUTH}\"" >> prometheus.web.yml
      - name: dump prom
        run: cat prometheus.web.yml
      - name: create network
        run: docker network create -d bridge course-platform || true
      - name: docker compose
        run: docker compose -f docker-compose.yml up --build --detach